const preset = (id, _name, _subtitle, profile) => Object.freeze({
  id,
  profile: Object.freeze({ ...profile }),
})

// These are authored identity recipes, not outfits. Every preset resolves to the
// same biped-v2 garment anchors, so changing character never removes clothing
// and every current or future catalogue item fits every preset.
export const CHARACTER_PRESETS = Object.freeze([
  preset('mia', 'Mia', 'Warm · playful', { frame: 'average', height: 'average', skinTone: 'warm-medium', faceShape: 'soft-round', eyeShape: 'almond', eyeColor: 'hazel', browStyle: 'soft', noseShape: 'button', mouthStyle: 'soft', complexionDetail: 'freckles-soft', facialHair: 'none', hairTexture: 'wavy', hairStyle: 'ponytail', hairColor: 'espresso', face: 'bright' }),
  preset('ari', 'Ari', 'Gentle · observant', { frame: 'slender', height: 'mid-tall', skinTone: 'golden-light', faceShape: 'oval', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'straight', noseShape: 'straight', mouthStyle: 'fine', complexionDetail: 'none', facialHair: 'stubble', hairTexture: 'wavy', hairStyle: 'shag', hairColor: 'dark-brown', face: 'soft' }),
  preset('nia', 'Nia', 'Radiant · bold', { frame: 'soft', height: 'average', skinTone: 'deep-golden', faceShape: 'heart', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'full', noseShape: 'rounded', mouthStyle: 'full', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'coily', hairStyle: 'afro', hairColor: 'soft-black', face: 'confident' }),
  preset('theo', 'Theo', 'Relaxed · clever', { frame: 'slender', height: 'tall', skinTone: 'golden', faceShape: 'long', eyeShape: 'almond', eyeColor: 'gray-green', browStyle: 'soft', noseShape: 'straight', mouthStyle: 'crooked-smile', complexionDetail: 'sun-kissed', facialHair: 'none', hairTexture: 'straight', hairStyle: 'side-part', hairColor: 'ink', face: 'bright' }),
  preset('imani', 'Imani', 'Poised · direct', { frame: 'athletic', height: 'mid-tall', skinTone: 'mahogany', faceShape: 'diamond', eyeShape: 'deep-set', eyeColor: 'coffee', browStyle: 'bold', noseShape: 'wide', mouthStyle: 'full', complexionDetail: 'beauty-mark', facialHair: 'none', hairTexture: 'braided', hairStyle: 'braided-bun', hairColor: 'ink', face: 'focused' }),
  preset('lucas', 'Lucas', 'Sunny · sociable', { frame: 'average', height: 'average', skinTone: 'peach', faceShape: 'square', eyeShape: 'round', eyeColor: 'blue', browStyle: 'full', noseShape: 'rounded', mouthStyle: 'wide', complexionDetail: 'freckles-full', facialHair: 'short-beard', hairTexture: 'curly', hairStyle: 'curly-top', hairColor: 'copper', face: 'bright' }),
  preset('sora', 'Sora', 'Quiet · precise', { frame: 'compact', height: 'mid-short', skinTone: 'golden-light', faceShape: 'heart', eyeShape: 'hooded', eyeColor: 'dark-brown', browStyle: 'fine', noseShape: 'button', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'none', hairTexture: 'straight', hairStyle: 'bob', hairColor: 'soft-black', face: 'thoughtful' }),
  preset('malik', 'Malik', 'Confident · kind', { frame: 'broad', height: 'tall', skinTone: 'umber', faceShape: 'square', eyeShape: 'deep-set', eyeColor: 'amber', browStyle: 'bold', noseShape: 'wide', mouthStyle: 'wide', complexionDetail: 'none', facialHair: 'full-beard', hairTexture: 'locs', hairStyle: 'loc-bun', hairColor: 'ink', face: 'confident' }),
  preset('elena', 'Elena', 'Lively · romantic', { frame: 'average', height: 'mid-short', skinTone: 'olive-light', faceShape: 'oval', eyeShape: 'upturned', eyeColor: 'green', browStyle: 'arched', noseShape: 'upturned', mouthStyle: 'bowed', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'curly', hairStyle: 'curls', hairColor: 'auburn', face: 'bright' }),
  preset('ren', 'Ren', 'Cool · thoughtful', { frame: 'slender', height: 'average', skinTone: 'olive-medium', faceShape: 'diamond', eyeShape: 'downturned', eyeColor: 'gray-blue', browStyle: 'straight', noseShape: 'straight', mouthStyle: 'fine', complexionDetail: 'beauty-mark', facialHair: 'none', hairTexture: 'straight', hairStyle: 'crop', hairColor: 'plum', face: 'thoughtful' }),
  preset('amara', 'Amara', 'Warm · artistic', { frame: 'soft', height: 'mid-tall', skinTone: 'deep', faceShape: 'soft-round', eyeShape: 'round', eyeColor: 'dark-brown', browStyle: 'full', noseShape: 'rounded', mouthStyle: 'full', complexionDetail: 'freckles-soft', facialHair: 'none', hairTexture: 'braided', hairStyle: 'braided-pony', hairColor: 'soft-black', face: 'soft' }),
  preset('felix', 'Felix', 'Curious · easygoing', { frame: 'compact', height: 'mid-short', skinTone: 'porcelain', faceShape: 'heart', eyeShape: 'almond', eyeColor: 'hazel', browStyle: 'soft', noseShape: 'button', mouthStyle: 'crooked-smile', complexionDetail: 'freckles-full', facialHair: 'mustache', hairTexture: 'wavy', hairStyle: 'shoulder-waves', hairColor: 'chestnut', face: 'bright' }),
  preset('zuri', 'Zuri', 'Bright · fearless', { frame: 'athletic', height: 'average', skinTone: 'espresso', faceShape: 'long', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'bold', noseShape: 'wide', mouthStyle: 'wide', complexionDetail: 'sun-kissed', facialHair: 'none', hairTexture: 'locs', hairStyle: 'loc-pony', hairColor: 'ink', face: 'confident' }),
  preset('jun', 'Jun', 'Focused · minimal', { frame: 'average', height: 'mid-tall', skinTone: 'golden-light', faceShape: 'square', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'straight', noseShape: 'straight', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'goatee', hairTexture: 'straight', hairStyle: 'buzz', hairColor: 'soft-black', face: 'focused' }),
  preset('cass', 'Cass', 'Soft · imaginative', { frame: 'soft', height: 'average', skinTone: 'alabaster', faceShape: 'soft-round', eyeShape: 'round', eyeColor: 'gray-blue', browStyle: 'fine', noseShape: 'upturned', mouthStyle: 'bowed', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'wavy', hairStyle: 'high-pony', hairColor: 'honey', face: 'soft' }),
  preset('mateo', 'Mateo', 'Grounded · witty', { frame: 'broad', height: 'average', skinTone: 'olive-medium', faceShape: 'oval', eyeShape: 'downturned', eyeColor: 'hazel', browStyle: 'full', noseShape: 'aquiline', mouthStyle: 'crooked-smile', complexionDetail: 'sun-kissed', facialHair: 'short-beard', hairTexture: 'curly', hairStyle: 'shag', hairColor: 'dark-brown', face: 'confident' }),
  preset('ayla', 'Ayla', 'Graceful · assured', { frame: 'slender', height: 'tall', skinTone: 'umber-light', faceShape: 'diamond', eyeShape: 'almond', eyeColor: 'amber', browStyle: 'arched', noseShape: 'straight', mouthStyle: 'full', complexionDetail: 'beauty-mark', facialHair: 'none', hairTexture: 'braided', hairStyle: 'braided-bob', hairColor: 'espresso', face: 'confident' }),
  preset('rowan', 'Rowan', 'Gentle · eccentric', { frame: 'compact', height: 'mid-short', skinTone: 'peach', faceShape: 'long', eyeShape: 'deep-set', eyeColor: 'green', browStyle: 'soft', noseShape: 'aquiline', mouthStyle: 'fine', complexionDetail: 'freckles-soft', facialHair: 'stubble', hairTexture: 'curly', hairStyle: 'top-knot', hairColor: 'copper', face: 'thoughtful' }),
  preset('simone', 'Simone', 'Elegant · exacting', { frame: 'average', height: 'mid-tall', skinTone: 'mahogany', faceShape: 'heart', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'arched', noseShape: 'rounded', mouthStyle: 'bowed', complexionDetail: 'none', facialHair: 'none', hairTexture: 'coily', hairStyle: 'twists', hairColor: 'soft-black', face: 'focused' }),
  preset('nico', 'Nico', 'Bold · playful', { frame: 'athletic', height: 'average', skinTone: 'golden', faceShape: 'square', eyeShape: 'round', eyeColor: 'blue', browStyle: 'bold', noseShape: 'button', mouthStyle: 'wide', complexionDetail: 'freckles-soft', facialHair: 'mustache', hairTexture: 'wavy', hairStyle: 'ponytail', hairColor: 'plum', face: 'bright' }),
  preset('meilin', 'Mei-Lin', 'Calm · polished', { frame: 'slender', height: 'mid-short', skinTone: 'golden-light', faceShape: 'oval', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'fine', noseShape: 'straight', mouthStyle: 'soft', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'straight', hairStyle: 'bun', hairColor: 'ink', face: 'soft' }),
  preset('darius', 'Darius', 'Steady · generous', { frame: 'broad', height: 'tall', skinTone: 'deep-golden', faceShape: 'long', eyeShape: 'deep-set', eyeColor: 'amber', browStyle: 'full', noseShape: 'wide', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'full-beard', hairTexture: 'locs', hairStyle: 'loc-bob', hairColor: 'soft-black', face: 'soft' }),
  preset('poppy', 'Poppy', 'Cheerful · crafty', { frame: 'soft', height: 'short', skinTone: 'porcelain', faceShape: 'soft-round', eyeShape: 'round', eyeColor: 'green', browStyle: 'arched', noseShape: 'button', mouthStyle: 'full', complexionDetail: 'freckles-full', facialHair: 'none', hairTexture: 'curly', hairStyle: 'curls', hairColor: 'copper', face: 'bright' }),
  preset('santiago', 'Santiago', 'Dapper · warm', { frame: 'average', height: 'mid-tall', skinTone: 'umber-light', faceShape: 'diamond', eyeShape: 'almond', eyeColor: 'hazel', browStyle: 'bold', noseShape: 'aquiline', mouthStyle: 'crooked-smile', complexionDetail: 'sun-kissed', facialHair: 'goatee', hairTexture: 'curly', hairStyle: 'curly-top', hairColor: 'espresso', face: 'confident' }),
  preset('salma', 'Salma', 'Poised · generous', { frame: 'soft', height: 'average', skinTone: 'olive-medium', faceShape: 'soft-round', eyeShape: 'almond', eyeColor: 'coffee', browStyle: 'arched', noseShape: 'straight', mouthStyle: 'full', complexionDetail: 'sun-kissed', facialHair: 'none', hairTexture: 'straight', hairStyle: 'bun', hairColor: 'dark-brown', face: 'soft' }),
  preset('bo', 'Bo', 'Cheerful · seasoned', { frame: 'compact', height: 'mid-short', skinTone: 'golden-light', faceShape: 'square', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'soft', noseShape: 'rounded', mouthStyle: 'wide', complexionDetail: 'sun-kissed', facialHair: 'mustache', hairTexture: 'straight', hairStyle: 'crop', hairColor: 'silver', face: 'bright' }),
  preset('priya', 'Priya', 'Confident · perceptive', { frame: 'average', height: 'mid-tall', skinTone: 'deep-golden', faceShape: 'oval', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'bold', noseShape: 'straight', mouthStyle: 'full', complexionDetail: 'none', facialHair: 'none', hairTexture: 'wavy', hairStyle: 'shoulder-waves', hairColor: 'soft-black', face: 'confident' }),
  preset('ade', 'Ade', 'Inventive · assured', { frame: 'athletic', height: 'average', skinTone: 'deep', faceShape: 'diamond', eyeShape: 'deep-set', eyeColor: 'dark-brown', browStyle: 'bold', noseShape: 'wide', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'none', hairTexture: 'coily', hairStyle: 'top-knot', hairColor: 'ink', face: 'confident' }),
  preset('ines', 'Inés', 'Lively · worldly', { frame: 'soft', height: 'short', skinTone: 'warm-medium', faceShape: 'heart', eyeShape: 'upturned', eyeColor: 'hazel', browStyle: 'arched', noseShape: 'upturned', mouthStyle: 'bowed', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'curly', hairStyle: 'bob', hairColor: 'silver', face: 'bright' }),
  preset('tomas', 'Tomas', 'Gentle · dependable', { frame: 'broad', height: 'average', skinTone: 'olive-medium', faceShape: 'soft-round', eyeShape: 'downturned', eyeColor: 'coffee', browStyle: 'full', noseShape: 'rounded', mouthStyle: 'soft', complexionDetail: 'sun-kissed', facialHair: 'full-beard', hairTexture: 'wavy', hairStyle: 'side-part', hairColor: 'silver', face: 'soft' }),
  preset('kofi', 'Kofi', 'Dignified · kind', { frame: 'broad', height: 'tall', skinTone: 'espresso', faceShape: 'long', eyeShape: 'deep-set', eyeColor: 'dark-brown', browStyle: 'full', noseShape: 'wide', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'full-beard', hairTexture: 'coily', hairStyle: 'buzz', hairColor: 'silver', face: 'soft' }),
  preset('val', 'Val', 'Fearless · expressive', { frame: 'slender', height: 'average', skinTone: 'porcelain', faceShape: 'diamond', eyeShape: 'almond', eyeColor: 'gray-blue', browStyle: 'bold', noseShape: 'aquiline', mouthStyle: 'fine', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'straight', hairStyle: 'buzz', hairColor: 'soft-black', face: 'confident' }),
  preset('noor', 'Noor', 'Calm · incisive', { frame: 'compact', height: 'mid-short', skinTone: 'golden', faceShape: 'heart', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'straight', noseShape: 'button', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'none', hairTexture: 'straight', hairStyle: 'crop', hairColor: 'ink', face: 'thoughtful' }),
  preset('mika', 'Mika', 'Gentle · luminous', { frame: 'slender', height: 'mid-tall', skinTone: 'alabaster', faceShape: 'heart', eyeShape: 'round', eyeColor: 'gray-blue', browStyle: 'fine', noseShape: 'button', mouthStyle: 'bowed', complexionDetail: 'freckles-soft', facialHair: 'none', hairTexture: 'coily', hairStyle: 'curls', hairColor: 'white', face: 'soft' }),
  preset('esther', 'Esther', 'Joyful · wise', { frame: 'soft', height: 'mid-short', skinTone: 'mahogany', faceShape: 'soft-round', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'arched', noseShape: 'wide', mouthStyle: 'full', complexionDetail: 'none', facialHair: 'none', hairTexture: 'locs', hairStyle: 'loc-bun', hairColor: 'silver', face: 'bright' }),
  preset('dev', 'Dev', 'Warm · meticulous', { frame: 'average', height: 'mid-tall', skinTone: 'umber', faceShape: 'oval', eyeShape: 'almond', eyeColor: 'coffee', browStyle: 'bold', noseShape: 'aquiline', mouthStyle: 'crooked-smile', complexionDetail: 'sun-kissed', facialHair: 'full-beard', hairTexture: 'wavy', hairStyle: 'bun', hairColor: 'silver', face: 'soft' }),
  preset('anjali', 'Anjali', 'Poised · warm', { frame: 'average', height: 'average', skinTone: 'deep-golden', faceShape: 'oval', eyeShape: 'almond', eyeColor: 'dark-brown', browStyle: 'full', noseShape: 'straight', mouthStyle: 'full', complexionDetail: 'none', facialHair: 'none', hairTexture: 'braided', hairStyle: 'braided-pony', hairColor: 'ink', face: 'confident' }),
  preset('arjun', 'Arjun', 'Open · quick-witted', { frame: 'athletic', height: 'mid-tall', skinTone: 'golden', faceShape: 'square', eyeShape: 'round', eyeColor: 'coffee', browStyle: 'full', noseShape: 'straight', mouthStyle: 'wide', complexionDetail: 'sun-kissed', facialHair: 'stubble', hairTexture: 'curly', hairStyle: 'curly-top', hairColor: 'espresso', face: 'bright' }),
  preset('kavya', 'Kavya', 'Calm · self-possessed', { frame: 'slender', height: 'average', skinTone: 'warm-medium', faceShape: 'diamond', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'bold', noseShape: 'aquiline', mouthStyle: 'fine', complexionDetail: 'beauty-mark', facialHair: 'none', hairTexture: 'wavy', hairStyle: 'crop', hairColor: 'ink', face: 'thoughtful' }),
  preset('lakshmi', 'Lakshmi', 'Kind · discerning', { frame: 'soft', height: 'short', skinTone: 'deep', faceShape: 'soft-round', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'arched', noseShape: 'rounded', mouthStyle: 'full', complexionDetail: 'none', facialHair: 'none', hairTexture: 'braided', hairStyle: 'braided-pony', hairColor: 'silver', face: 'soft' }),
  preset('sameer', 'Sameer', 'Assured · thoughtful', { frame: 'broad', height: 'average', skinTone: 'umber-light', faceShape: 'long', eyeShape: 'deep-set', eyeColor: 'coffee', browStyle: 'full', noseShape: 'aquiline', mouthStyle: 'soft', complexionDetail: 'sun-kissed', facialHair: 'mustache', hairTexture: 'wavy', hairStyle: 'side-part', hairColor: 'silver', face: 'confident' }),
  preset('meera', 'Meera', 'Bright · perceptive', { frame: 'average', height: 'mid-short', skinTone: 'golden', faceShape: 'heart', eyeShape: 'round', eyeColor: 'coffee', browStyle: 'soft', noseShape: 'straight', mouthStyle: 'bowed', complexionDetail: 'rosy', facialHair: 'none', hairTexture: 'curly', hairStyle: 'curls', hairColor: 'silver', face: 'bright' }),
  preset('aiko', 'Aiko', 'Gentle · insightful', { frame: 'compact', height: 'mid-short', skinTone: 'golden-light', faceShape: 'oval', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'fine', noseShape: 'straight', mouthStyle: 'soft', complexionDetail: 'none', facialHair: 'none', hairTexture: 'straight', hairStyle: 'bob', hairColor: 'silver', face: 'soft' }),
  preset('minjun', 'Min-jun', 'Steady · composed', { frame: 'average', height: 'mid-tall', skinTone: 'olive-light', faceShape: 'square', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'straight', noseShape: 'straight', mouthStyle: 'fine', complexionDetail: 'none', facialHair: 'stubble', hairTexture: 'straight', hairStyle: 'side-part', hairColor: 'silver', face: 'thoughtful' }),
  preset('linh', 'Linh', 'Lively · observant', { frame: 'slender', height: 'average', skinTone: 'golden', faceShape: 'heart', eyeShape: 'upturned', eyeColor: 'dark-brown', browStyle: 'arched', noseShape: 'button', mouthStyle: 'full', complexionDetail: 'beauty-mark', facialHair: 'none', hairTexture: 'straight', hairStyle: 'shoulder-waves', hairColor: 'ink', face: 'bright' }),
  preset('siti', 'Siti', 'Welcoming · graceful', { frame: 'soft', height: 'average', skinTone: 'warm-medium', faceShape: 'soft-round', eyeShape: 'almond', eyeColor: 'coffee', browStyle: 'soft', noseShape: 'rounded', mouthStyle: 'full', complexionDetail: 'none', facialHair: 'none', hairTexture: 'straight', hairStyle: 'bun', hairColor: 'dark-brown', face: 'soft' }),
  preset('tala', 'Tala', 'Energetic · assured', { frame: 'athletic', height: 'mid-short', skinTone: 'olive-medium', faceShape: 'diamond', eyeShape: 'almond', eyeColor: 'hazel', browStyle: 'bold', noseShape: 'upturned', mouthStyle: 'wide', complexionDetail: 'freckles-soft', facialHair: 'none', hairTexture: 'wavy', hairStyle: 'bob', hairColor: 'dark-brown', face: 'confident' }),
  preset('wei', 'Wei', 'Composed · inventive', { frame: 'slender', height: 'mid-tall', skinTone: 'golden-light', faceShape: 'long', eyeShape: 'hooded', eyeColor: 'coffee', browStyle: 'straight', noseShape: 'straight', mouthStyle: 'fine', complexionDetail: 'none', facialHair: 'goatee', hairTexture: 'straight', hairStyle: 'side-part', hairColor: 'ink', face: 'focused' }),
])

export function characterPreset(id) {
  return CHARACTER_PRESETS.find((entry) => entry.id === id) || CHARACTER_PRESETS[0]
}
