import {CLOCK_PHASES} from './game-clock.js'
import {FASHION_FABRICS, FASHION_SCHEMATICS} from './fashion-catalog.js'
import {compatibleFashionFabric} from './fashion-types.js'
import {incomeForecast} from './economy.js'

export function economyJournalMarkup(journal, playtest=false) {
  if(!journal) return '<h2>Town journal</h2><p>The atelier is opening.</p>'
  const {clock,ledger,forecasts,progression,collections}=journal
  const mixed=forecasts.find(item=>item.id==='mixed')
  const baselineMixed=incomeForecast('starter').find(item=>item.id==='mixed')
  const next=progression.nextMilestone
  const gap=next ? Math.max(0,next.requirements[0].target-progression.stats.coinsEarned) : 0
  const projectCosts=FASHION_SCHEMATICS.filter(item=>item.unlockLevel<=progression.atelierLevel).map(pattern=>{
    const materials=FASHION_FABRICS.filter(f=>f.unlockLevel<=progression.atelierLevel && compatibleFashionFabric(pattern,f))
    return Math.min(...materials.map(f=>f.cost*pattern.materialUnits))
  }).filter(Number.isFinite)
  const history=ledger.history.slice(-3).reverse()
  return `<span class="hub-drawer-eyebrow">The town ledger</span><h2 tabindex="-1">Your day, your atelier</h2>
    <p>A day lasts <b>24 minutes</b> of visible, unpaused play, from 06:00 to the next 06:00. Time advances on its own—not when an order or garment finishes. Hidden tabs and offline time do not count.</p>
    <div class="economy-rhythm" aria-label="Automatic day cycle">${CLOCK_PHASES.map(phase=>`<span class="${phase.id===clock.phase?'is-current':''}"><b>${phase.label}</b><small>${String(Math.floor(phase.start/60)).padStart(2,'0')}:00–${String(Math.floor(phase.end/60)).padStart(2,'0')}:00</small><em>${phase.seconds/60} real min</em></span>`).join('')}</div>
    <p>New shelf offers arrive at dawn. Shops and service stay open overnight. Paid projects carry over safely. Pause the day clock for planning; working at a station resumes it automatically.</p>
    <div class="hub-shop-summary"><span><b>${ledger.current.earned} ●</b><small>earned today</small></span><span><b>${ledger.current.spent} ●</b><small>spent today</small></span><span><b>${ledger.current.pizzas} / ${ledger.current.garments}</b><small>orders / garments</small></span></div>
    <h3>Plan a day</h3><div class="economy-forecasts">${forecasts.map(plan=>`<article><b>${plan.label}</b><strong>~${plan.gross} ●</strong><small>${plan.orders} pizzas · ${plan.quality}% match</small><small>${plan.dishes} dishes + ${plan.sodas} sodas: ${plan.bonusGross} bonus ●</small><small>~${plan.serviceMinutes.toFixed(1)} min including prep</small></article>`).join('')}</div>
    <p class="economy-small">A mixed day budgets about a minute per pizza; focused service aims for 40–45 seconds as you learn the controls. Batch prep is shared across five orders. Twelve pizzas plus some dishes and sodas leave time for two garments and browsing. Estimates use an even mix of your menu (${journal.tier}); handmade presentation and reputation loyalty are included, conditional sets are not. These are planning examples, not a daily limit—faster players can serve more.</p>
    <h3>Kitchen rhythm</h3><p>Throw dough and prepare sauce before building a pizza. Each pizza consumes one dough skin and one portion of the correct sauce; a batch makes five portions. Tomato sauce warns after three minutes on duty and burns after four: <b>cooking stops until you stir 1¼ turns to rescue it</b>. Stir ¾ turn for routine upkeep. The heat diffuser slows heating 30%. Cold pesto never burns. Leaving service, pausing, or hiding the tab banks the heat rather than resetting it.</p>
    <p>Each served pizza creates two dirty dishes and one soda order. A scrubbed, rinsed dish pays <b>2 ●</b>; a correct, careful soda pour pays <b>3–8 ●</b> (very poor or wrong-flavor pours pay nothing). Prep itself earns no cash. Restarting a station cannot create customers or duplicate rewards. Today's service bonuses: <b>${ledger.current.bonusCoins || 0} ●</b> from ${ledger.current.dishes || 0} dishes and ${ledger.current.sodas || 0} sodas. House supplies are free; your saved prep and unfinished pizza carry over.</p>
    <p><b>Craft or buy:</b> Mara sells 3–5 patterns per day for about 12% of the matching ready-made price. Buy once and keep them forever in <b>My pattern box</b>; only owned patterns appear at the cutting table. New purchases are highlighted and sorted first; value and atelier-tier sorts help browse your collection. Shipments rotate at dawn, with higher-level designs entering future shipments as the atelier grows. Each repeat project then costs around ${Math.min(...projectCosts)}–${Math.max(...projectCosts)} coins with the cheapest suitable material, before optional alterations. Shelf materials and featured ready-made pieces are 10% off. Standard supplies and unlocked ready-made pieces never disappear. Materials are purchased once when cutting begins; there is no separate supply bag. Garment appraisal is not a cash reward.</p>
    <h3>Clothing progression</h3><p>${next?`Next: <b>atelier ${next.level} · ${next.label}</b>. ${gap} more lifetime service coins—about ${Math.ceil(gap/(mixed.gross/mixed.orders))} typical orders with some dish/soda bonuses. `:'Every collection is unlocked. '}Spending never removes progress. Equipment and perfection are not required; steady crafting offers a 15% income shortcut.</p>
    <div class="economy-table-wrap"><table class="economy-unlocks"><thead><tr><th>Atelier</th><th>Lifetime coins</th><th>New pieces / patterns</th><th>Mixed-day target*</th></tr></thead><tbody>${collections.map(item=>`<tr class="${item.level<=progression.atelierLevel?'is-unlocked':''}"><td>${item.level}${item.level<=progression.atelierLevel?' ✓':''}</td><td>${item.requirements[0]?.target || 0}</td><td>${item.pieces} / ${item.patterns}</td><td>${item.level===1?'Start':`Day ${Math.ceil(item.requirements[0].target/baselineMixed.gross)}`}</td></tr>`).join('')}</tbody></table></div>
    ${next?.shortcut?`<p class="economy-small">Optional shortcut for atelier ${next.level}: ${next.shortcut.income} lifetime coins, ${next.shortcut.garments} finished garments, and ${next.shortcut.accuracy}% best construction accuracy.</p>`:''}
    <p class="economy-small">*Starter-menu estimate from a new game, including dish/soda income but no outfit or loyalty bonuses—not a calendar gate. Better counters, faster orders and craft shortcuts can bring unlocks forward. Existing saves retain their unlocked levels.</p>
    <h3>Outfit benefits</h3><p>Handmade quality grants up to 8% presentation. Counter, vegetable and evening sets add situational tips; <b>all clothing income bonuses together cap at 15%</b>. Maker sets save 8–15% on project costs, Plum sets add 3–6 finish points, and Sunday sets add 4–8% reputation (fractions carry forward). Altering a set piece keeps its set credit. Different colorways do not multiply a bonus. Neighborhood reputation separately adds up to 6% loyalty income at 240 rep; currently +${((journal.loyalty || 0)*100).toFixed(1)}%.</p>
    ${history.length?`<h3>Recent days</h3><div class="economy-history">${history.map(day=>`<p><b>Day ${day.day}</b> · +${day.earned} earned / −${day.spent} spent · ${day.pizzas} orders / ${day.garments} garments · closed with ${day.closingBalance} ●</p>`).join('')}</div>`:''}
    <div class="hub-drawer-button-row"><button class="hub-drawer-primary" type="button" data-journal-clock-toggle>${clock.paused?'Resume day clock':'Pause day clock'}</button><button class="hub-drawer-secondary" type="button" data-close-drawer>Back to town</button></div>
    ${playtest?'<button class="hub-drawer-secondary economy-test-clock" type="button" data-test-clock-advance>Advance 6 minutes · test only</button>':''}`
}
